### PR TITLE
Do not look for version number on editable pip packages

### PR DESCRIPTION
**Pull request by cgibb**
If the user has a local python site and installed editable packages,
they will appear in the output of `pip freeze` in a different format
than other installed packages.

### Testing
Tested on Ubuntu as normal user with an editable copy of `colcon-bundle` installed.  `colcon bundle` succeeds in my catkin workspace.

### CODE REVIEW

**Comment by murphm8** [comment]
Hmm, so does this mean that `pip freeze` is giving us the versions of all the packages installed into the local environment and the bundle?

**Comment by cgibb** [comment]
The python interpreter in the bundle is actually also pulling in the system pip module rather than the one in the bundle. 

When running from my workspace:
```
$ ./bundle/bundle_staging/usr/bin/python3 -m pip --version
pip 19.0.3 from $HOME/.local/lib/python3.5/site-packages/pip (python 3.5)
```

So an alternative could be altering the python path configuration.

**Comment by murphm8** [comment]
Per our discussion: We should use the command line options to ignore the system paths when invoking Python.

**Comment by cgibb** [comment]
Fixed the formatting and merged in latest changes from /master. 

I haven't figured out a way to ignore the system paths and still produce a proper bundle, so I think the solution here is what we should use for now (as system libraries haven't been causing any other problems that we know of).

**Comment by murphm8** [comment]
I filed #40 to follow up on the issues exposed in this PR.

**Pull request merged**
