### PR TITLE
Respect ignore marker even if dangling symlink

### PR DESCRIPTION
**Pull request by rotu**
As per https://github.com/ros-infrastructure/rep/pull/256

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Have you tried running the patch?

**Comment by rotu** [comment]
> Have you tried running the patch?

I hadn't, as can be seen from CI!

**Comment by rotu** [comment]
This patch now works correctly and is ready for review

**Comment by dirk-thomas** [comment]
With the REP update merged (ros-infrastructure/rep#256) this can be merged whenever the maintainers are ready.

**Pull request merged**
