### PR TITLE
Add metrics logging to workflow

### PR DESCRIPTION
**Pull request by piraka9011**
* Add the CW Metrics GH Action to the testing workflow.

See the unit test job of #136 for an example of a successful run and #135 for an example of a failed run.

Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>

### CODE REVIEW

**Comment by thomas-moulard** [comment]
The two runs you're linking are using different versions of the action, any chance we could re-do that on top of master (with I guess the minimum change allowing the CW logic to happen in the PR).

**Comment by piraka9011** [comment]
> @thomas-moulard: I think it would be preferable to do the select this way: `if: github.event_name == 'schedule'`

This makes sense.

> Could we enable this all the time (for PRs, etc.)? Do we log the github.ref in CW? I imagine it can also create issues for personal forks where AWS is not setup though (no available secrets).

I'm worried if we do that then we get a lot of noise that will be hard to filter out in CW. We do have a filter for if the metric is a cron/schedule job, but I think this is best suited for monitoring canaries and not development PRs.

> I guess we need to setup the secrets before merging this? Are we ready to merge? I'll approve once the secrets are setup.

The secrets are already setup. Otherwise this wouldn't have worked 😅.

**Comment by piraka9011** [comment]
> This looks fine. I'm not thrilled to see all the copy-pasted blocks but I don't have a good idea how we can avoid it

Unfortunately we can't aggregate job steps at the moment...

**Comment by piraka9011** [comment]
Travis failed due to a connection error. Restarting.

**Comment by thomas-moulard** [comment]
@piraka9011 Secrets for the prod account

**Pull request merged**
